version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: 'circleci/golang'
    steps:
      - checkout
      - run: go mod download
      - run:
          name: "Create a temp directory for artifacts"
          command: |
            mkdir -p /tmp/test-results/jest/
            go install gotest.tools/gotestsum@latest
            go install github.com/axw/gocov/gocov@latest
            go install github.com/AlekSi/gocov-xml@latest
      - run:
          command: |
            gotestsum --junitfile gotestsum-report.xml
            mv gotestsum-report.xml /tmp/test-results/jest/
      - run:
          command: |
            gocov test | gocov-xml > coverage.xml
            cp coverage.xml /tmp/artifacts
      - codecov/upload:
          file: coverage.xml
      - store_artifacts:
          path: /tmp/artifacts
      - store_test_results:
          path: /tmp/test-results