version: 2.1
orbs:
  go: coveralls/coveralls@1.0.6
jobs:
  build:
    docker:
      - image: 'circleci/go@1.7.1'
    steps:
      - checkout
      - run: go mod download
      - run:
          name: "Create a temp directory for artifacts"
          command: |
            mkdir -p /tmp/test-results/jest/
            go install gotest.tools/gotestsum@latest
      - run:
          command: |
            gotestsum --junitfile gotestsum-report.xml
            mv gotestsum-report.xml /tmp/test-results/jest/
      - run:
          command: |
            go test -coverprofile=c.out
            go tool cover -html=c.out -o coverage.html
            mv coverage.html /tmp/artifacts
      - coveralls/upload
      - store_artifacts:
          path: /tmp/artifacts
      - store_test_results:
          path: /tmp/test-results

notify:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=${process.env.COVERALLS_REPO_TOKEN}