version: 2.1
orbs:
  go: circleci/go@1.7.1
jobs:
  build:
    executor:
      name: go/default
      tag: "1.16"
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run:
          name: "Create a temp directory for artifacts"
          command: |
            mkdir -p /tmp/test-results/jest/
            go install gotest.tools/gotestsum@latest
      - run:
          command: |
            gotestsum --junitfile gotestsum-report.xml
            mv gotestsum-report.xml /tmp/test-results/jest/
      - run:
          command: |
            go test -coverprofile=c.out
            go tool cover -html=c.out -o coverage.html
            mv coverage.html /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
      - store_test_results:
          path: /tmp/test-results
